/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js projects and kept here so TypeScript-aware
// editors understand the app router skeleton before dependencies are installed.
